server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://13.125.198.59:3100/loki/api/v1/push

scrape_configs:
  - job_name: access
    static_configs:
      - targets:
          - localhost
        labels:
          job: access
          __path__: /var/app/current/logs/access/access.log